travis:
  secure:
    BINSTAR_TOKEN: oKyQTz7U/HmagluiDsNYxMzxQbJ9UX/hgRyeaPEtlhgw2RLtY8vluL/806un93DAVqsHXSQmFa+JGx1YreKpNpc0j/YLglzRnbYYo8iS+VdZuYKCTPgq3QWvxCl/O8wrqLe/XIB58IRdVtUKgmNVuAXrYem9VyHPEbPkwG2j5VKNiHUp2dlAIb/IWXMVJyy6sp2VOIeyKB9hFYhyO7i1y4WxeeW4GC1ThTBOL07qBA2Noye0QpDn8c9A0muOb9jjtrm4DbdDURD/h8BvJ0lQzjSfvh03pPPAV4Cu26AvyCE4f6OKTBlBS6178cW0Kwjc8bCjCu9oBcGlsvEfJVhzfGQ9Sc1CNem4CFc5iloIyK0wneVrdQ1zpFQEG8L9n6I14GaKm1ZWF3nhyPnsTwK2sWjYQmrhbhVMIyyeWgA4bwg2XQHEgjhFndqfhWa4ImF8RiYUqofkw1GciB/mwyh8ur5qmfJ2xLi3D8Mt1j3cplhdK+s7qgcrijJV46HOcKQtg0e3L2Bo7Bpx5rE4cVjBUT5P1HQQIDcXCf2nrGxLjYz0jYubkpOTR7JGqb/8H4euenqkItjJMkKLPAp4kMieaiXL/epgV9ItDcpoi7g7p9D0pQ8BmxWytu4cptorU2cHpwa1PuWRKwSYrEtjxZ8IJIYNEZ2a5Zdj/ZwbuuUFp30=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
